### ISSUE TITLE
Compatibility issues with kreait/laravel-firebase 1.9

### ISSUE THREAD

**Issue by Chrisissorry** [firevel/firebase-authentication#11]
Hey there, 

I've noticed a compatibility issue beginning with `1.9` version of `kreait/laravel-firebase` as the `Verifier` was deprecated. 

I'd love to contribute, so let me know if you would take some time to review a PR.

Thanks

**Comment by sl0wik** [comment]
Hi,

Sure - contributions are welcome.

I got a concept for version 2.0 of this library where `->user()` returning `FirebaseUser` model instead of regular User model. It will make things much easier on micro services.
